language: ruby
dist: xenial
group: edge
cache:
  directories:
  - "${HOME}/bin"
  - "${HOME}/.cache/travis-terraform-config"
  bundler: true
env:
  global:
  - PATH="${HOME}/bin:${PATH}"
  - TMPDIR="${TMPDIR:-/tmp}"
before_install:
- eval "$(gimme 1.11.1)"
- make deps
script:
- make test
- make assert-clean
